config/routes.rb
Rails.application.routes.draw do

  get 'doc/v2'

  mount WeixinRailsMiddleware::Engine, at: "/"
  mount Ckeditor::Engine => '/ckeditor'

  resources :static_pages

  resources :home do
    get 'new_index', on: :collection
  end

  resources :posts do
    collection do
      get 'about_us'
      get 'knowledge'
      get '/:tag_id/:slug', action: 'show', as: 'slug'
      get '/:tag_id', action: 'posts_list', as: 'list'
    end
  end

  resources :wx, controller: :weixin  do
    get 'transform', on: :collection
  end

  resources :cities do
    post 'set'
    get 'city_capacity', on: :collection
  end

  resources :orders do
    member do
      post 'comment'
    end

    collection do
      get 'new_car_select'
      get 'new_service_select'
      get 'new_info_submit'

      get 'select_car'
      get 'select_item'
      get 'success'
      get 'order_status'

      get 'select_car_by_initial'
      get 'select_car_item'
      get 'auto_brands'
      get 'auto_series'
      get 'auto_model_numbers'
      get 'place_order_page'

      post 'refresh_price'
      post 'place_order'
      post 'submit'
      post 'validate_preferential_code'
      post 'no_preferential'
      get  'no_car_type'
      post 'submit_no_car_order'
      get  'pay_show'
      post 'pay'
      get 'notify'
    end
  end

  resources :users do
    collection do
      get 'orders'
      get 'orders_detail'
      get 'discounts'
      get 'maintain_histories_list'
      get 'maintain_history'
      get 'cars'
      get 'balance'
      get 'settings'
      get 'get_user_info'
    end
  end

  resources :service_addresses do
    post 'set_default'
  end

  resources :autos

  root to: 'home#new_index'

  resources :sessions do
    get 'callback',  on: :collection
    get 'notify', on: :collection
    delete 'destroy', on: :collection
  end

  namespace :admin do
    root to: 'main#index'
    resources :main
    resources :activities
    resources :channels
    resources :users
    resources :posts
    resources :cities
    resources :products
    resources :public_accounts do
      collection do
        get 'apply_menu' => 'public_accounts#apply_menu'
        get 'diy_menu' => 'public_accounts#diy_menu'
        get 'edit_menu' => 'public_accounts#edit_menu'
        post ':id/update_menu' => 'public_accounts#update_menu', as: 'update_menu'
      end
    end
    resources :qrcodes
    resources :weixin
    resources :reply_messages do
      resources :reply_articles
    end
  end

  namespace :activity do
    resources :main do
      collection do
        get 'select_city'
      end
    end
  end

  resources :phones do
    post :send_verification_code, on: :collection
  end

  get 'activities/:name' => 'activity/main#show', as: 'activity'
end

app/views/layouts/new/_footer.html.erb
<div class="kld-footer clearfix">
	<%= image_tag("new-index/logo2.png",:class => 'logo')%>
	<div class="copy">
		<span>Copyright © 2015 kalading.com</span>
		<span>备案号：京ICP备14006393号</span>    
		<span>京公网安备11010502026969</span>   
		<span>经营许可编号：京A2-1286578 营业执照</span>
	</div>
</div>

app/views/layouts/new/_header.html.erb
<nav class="header">
  <div class="kld-header">

    <ul class="cb-slideshow">
      <li><span>Image 01</span><div><h3></h3></div></li>
      <li><span>Image 02</span><div><h3></h3></div></li>
      <li><span>Image 03</span><div><h3></h3></div></li>
      <li><span>Image 04</span><div><h3></h3></div></li>
      <li><span>Image 05</span><div><h3></h3></div></li>
      <li><span>Image 06</span><div><h3></h3></div></li>
    </ul>

    <div class="kld-header-wrap">
      <div class="kld-header-logo">
        <a href="/" class="kld-header-logo-img">
          <%= image_tag("new-index/logo.png",:class => 'logo')%>
          <%= image_tag("new-index/logo-red.png",:class => 'logored hide')%>
        </a>
        <div class="kld-header-logo-slogan">
          <%= image_tag("new-index/slogan-1.png",:class => 'slogan1')%>
          <%= image_tag("new-index/slogan-2.png",:class => 'slogan2 hide')%>
        </div>
        <div class="dropdown address" title="服务地址">
          <a href="#">
            <span class="val">
              <span class="city"><%= current_city_name %></span>
              <span class="caret"></span>
            </span>
          </a>
        </div>
      </div>
      <ul class="kld-header-link">
        <li class="home <%= "active" if params[:action] == "new_index" %>">
          <a href="/" target="_blank">首页</a>
        </li>
        <li class="products <%= "active" if params[:action] == "new_car_select" %>">
          <a href="/orders/new_car_select?type=bmt" class="" onclick="return false;">预约服务</a>

          <div class="sub">
            <!-- <div class="bac"></div> -->
            <ul class="product clearfix">
              <li>
                <a href="/orders/new_car_select?type=bmt">
                  <p class="key hide">机油三滤</p>
                  <%= image_tag("new-index/bmt1.png",:class => 'pic1')%>
                  <%= image_tag("new-index/bmt2.png",:class => 'pic2 hide')%>
                </a>
              </li>
              <li>
                <a href="/orders/new_car_select?type=smt">
                  <p class="key hide">机油机滤</p>
                  <%= image_tag("new-index/smt1.png",:class => 'pic1')%>
                  <%= image_tag("new-index/smt2.png",:class => 'pic2 hide')%>
                </a>
              </li>
              <li>
                <a href="/orders/new_car_select?type=pm25">
                  <p class="key hide">空调滤清器</p>
                  <%= image_tag("new-index/pm25.png",:class => 'pic1')%>
                  <%= image_tag("new-index/pm252.png",:class => 'pic2 hide')%>
                </a>
              </li>
              <li>
                <a href="/orders/new_car_select?type=bty">
                  <p class="key hide">更换电瓶</p>
                  <%= image_tag("new-index/battery1.png",:class => 'pic1')%>
                  <%= image_tag("new-index/battery2.png",:class => 'pic2 hide')%>
                </a>
              </li>
            </ul>
          </div>
        </li>

        <li class="service <%= "active" if params[:action] == "new_service_select" %>">
          <a href="/static_pages/fu-wu-liu-cheng" class="cl-effect-1" target="_blank">服务介绍</a>
        </li>

        <li class="team">
          <%= link_to "城市团队", static_page_path(id: 'fu-wu-cheng-shi'), "target" => '_blank', class: 'cl-effect-1' %>
          <div class="sub hide">
            <div class="subbac"></div>
            <ul>
              <li>
                <a href="">服务城市</a>
              </li>
              <li>
                <a href="">团队风采</a>
              </li>
            </ul>
          </div>
        </li>

        <li class="about">
          <a href="/static_pages/qi-ye-jie-shao" target="_blank" class="cl-effect-1">关于我们</a>
          <div class="sub hide">
            <div class="subbac"></div>
            <ul class="clearfix">
              <li>
                <a href="">联系我们</a>
              </li>
            </ul>
          </div>
        </li>
        <li class="knowledge">
          <%= link_to "用车知识", slug_posts_path(20, 'knowledge'), "target" => "_blank", class: 'cl-effect-1' %>
        </li>
        <li class="log-btn <%= "active" if params[:action] == "orders" || params[:action] == "maintain_histories_list" || params[:action] == "orders_detail" %>">
          <% if !signed_in? %>
            <a href="#" id="login_btn" class="cl-effect-1">
              登录
            </a>
          <% else %>
            <%= link_to "个人中心", orders_users_path, class: 'cl-effect-1' %>
            <div class="sub hide">
              <div class="subbac"></div>
              <ul class="clearfix">
                <li>
                  <%= link_to "我的订单", orders_users_path %>
                </li>
                <li>
                  <%= link_to "保养记录", maintain_histories_list_users_path %>
                </li>
                <li>
                  <%= link_to '登出', sessions_path, method: :delete %>
                </li>
              </ul>
            </div>

          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/new/_header_others.html.erb
<nav class="header-others">
  <div class="kld-header">
    <div class="bac"></div>
    <div class="kld-header-wrap">
      <div class="kld-header-logo">
        <a href="/" class="kld-header-logo-img">
          <%= image_tag("new-index/logo.png")%>
        </a>
        <div class="kld-header-logo-slogan">
          <%= image_tag("new-index/slogan-1.png")%>
        </div>
        <div class="address" title="服务地址">
          <a href="#">
            <span class="val">
              <span class="city"><%= current_city_name %></span>
              <span class="caret"></span>
            </span>
          </a>
        </div>
      </div>
      <% id = params[:id] %>
      <% type = params[:type] %>
      <% action = params[:action] %>
      <% controller = params[:controller] %>
      <ul class="kld-header-link">
        <li class="home <%= "active" if action == "new_index" %>">
          <a href="/" class="cl-effect-1">首页</a>
        </li>
        <li class="products <%= "active" if ['new_car_select','new_service_select','new_info_submit'].include?(action) %>">
          <a href="/orders/new_car_select?type=bmt"  class="cl-effect-1">预约服务</a>

          <div class="sub2 hide">
            <div class="subbac"></div>
            <ul class="clearfix">
              <li class="<%= "active" if type == 'bmt' %>">
                <%= link_to "机油三滤", new_car_select_orders_path(type: 'bmt'), class: 'order-btn', "data-type" => "bmt" %>
              </li>
              <li class="<%= "active" if type == 'smt' %>">
                <%= link_to "机油机滤", new_car_select_orders_path(type: 'smt'), class: 'order-btn', "data-type" => "smt" %>
              </li>
              <li class="<%= "active" if type == 'pm25' %>">
                <%= link_to "PM2.5空调滤芯", new_car_select_orders_path(type: 'pm25'), class: 'order-btn', "data-type" => "pm25" %>
              </li>
              <li class="<%= "active" if type == 'bty' %>">
                <%= link_to "更换电瓶", new_car_select_orders_path(type: 'bty'), class: 'order-btn', "data-type" => "bty" %>
              </li>
            </ul>
          </div>

        </li>
        <li class="service <%= "active" if controller == "static_pages" && action == "show" && ['fu-wu-liu-cheng','ji-you-san-lv','ji-you-ji-lv','pm25','geng-huan-dian-ping','an-quan-32'].include?(id) %>">
          <a href="/static_pages/fu-wu-liu-cheng" class="cl-effect-1">服务介绍</a>

          <div class="sub2 hide">
            <div class="subbac"></div>
            <ul class="clearfix">
              <li class="<%= "active" if id == 'fu-wu-liu-cheng' %>">
                <%= link_to "服务流程", static_page_path(id: 'fu-wu-liu-cheng') %>
              </li>
              <li class="<%= "active" if id == 'ji-you-san-lv' %>">
                <%= link_to "机油三滤", static_page_path(id: 'ji-you-san-lv') %>
              </li>
              <li class="<%= "active" if id == 'ji-you-ji-lv' %>">
                <%= link_to "机油机滤", static_page_path(id: 'ji-you-ji-lv') %>
              </li>
              <li class="<%= "active" if id == 'pm25' %>">
                <%= link_to "PM2.5空调滤芯", static_page_path(id: 'pm25') %>
              </li>
              <li class="<%= "active" if id == 'geng-huan-dian-ping' %>">
                <%= link_to "更换电瓶", static_page_path(id: 'geng-huan-dian-ping') %>
              </li>
              <li class="<%= "active" if id == 'an-quan-32' %>">
                <%= link_to "32项安全检测", static_page_path(id: 'an-quan-32') %>
              </li>
            </ul>
          </div>
        </li>
        <li class="team <%= "active" if controller == "static_pages" && ['fu-wu-cheng-shi','tuan-dui-feng-cai'].include?(id) %>">
          <a href="/static_pages/fu-wu-cheng-shi" class="cl-effect-1" class="cl-effect-1">城市团队</a>
          <div class="sub2 hide">
            <div class="subbac"></div>
            <ul>
              <li class="<%= "active" if id == 'fu-wu-cheng-shi' %>">
                <a href="/static_pages/fu-wu-cheng-shi">服务城市</a>
              </li>
              <li class="<%= "active" if id == 'tuan-dui-feng-cai' %>">
                <a href="/static_pages/tuan-dui-feng-cai">团队风采</a>
              </li>
            </ul>
          </div>
        </li>

        <li class="about <%= "active" if ['static_pages','posts'].include?(controller) && ['posts_list','show'].include?(action) && (['qi-ye-jie-shao','fu-wu-ke-hu','qi-ye-rong-yu','lian-xi-wo-men'].include?(id) || params[:tag_id] == '15') %>">
          <a href="/static_pages/qi-ye-jie-shao" class="cl-effect-1">关于我们</a>
          <div class="sub2 hide">
            <div class="subbac"></div>
            <ul class="clearfix">

              <li class="<%= "active" if id == "qi-ye-jie-shao" %>">
                <a href="/static_pages/qi-ye-jie-shao">企业介绍</a>
              </li>
              <li class="<%= "active" if id == "fu-wu-ke-hu" %>">
                <a href="/static_pages/fu-wu-ke-hu">服务客户</a>
              </li>
              <li class="<%= "active" if id == "qi-ye-rong-yu" %>">
                <a href="/static_pages/qi-ye-rong-yu">企业荣誉</a>
              </li>
              <li class="<%= "active" if id == "lian-xi-wo-men" %>">
                <a href="/static_pages/lian-xi-wo-men">联系我们</a>
              </li>
              <li class="<%= "active" if params[:tag_id] == '15' %>">
                <%= link_to "媒体报道", list_posts_path(tag_id: 15) %>
              </li>
            </ul>
          </div>
        </li>

        <li class="knowledge <%= "active" if controller == "posts" && ['posts_list','show'].include?(action) && params[:tag_id] == '23' %> ">
          <%= link_to "用车知识", list_posts_path(tag_id: 23), class: 'cl-effect-1' %>
        </li>

        <li class="log-btn <%= "active" if controller == "users" %>">
          <% if !signed_in? %>
            <a href="#" id="login_btn" class="cl-effect-1">
              登录
            </a>
          <% else %>
            <%= link_to "个人中心", orders_users_path, class: 'cl-effect-1' %>
            <div class="sub2 hide">
              <div class="subbac"></div>
              <ul class="clearfix">
                <li class="<%= "active" if controller == "users" && action == "orders" %>">
                  <%= link_to "我的订单", orders_users_path %>
                </li>
                <li class="<%= "active" if controller == "users" && ['maintain_histories_list','maintain_history'].include?(action) %>">
                  <%= link_to "保养记录", maintain_histories_list_users_path %>
                </li>
                <li class="<%= "active" if controller == "users" && action == "discount" %>">
                  <%= link_to "优惠券", discounts_users_path %>
                </li>
                <li>
                  <%= link_to '登出', sessions_path, method: :delete %>
                </li>
              </ul>
            </div>

          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>