config/routes.rb
Rails.application.routes.draw do

  get 'doc/v2'

  mount WeixinRailsMiddleware::Engine, at: "/"
  mount Ckeditor::Engine => '/ckeditor'

  resources :static_pages

  resources :home do
    get 'new_index', on: :collection
  end

  resources :posts do
    collection do
      get 'about_us'
      get 'knowledge'
      get '/:tag_id/:slug', action: 'show', as: 'slug'
      get '/:tag_id', action: 'posts_list', as: 'list'
    end
  end

  resources :wx, controller: :weixin  do
    get 'transform', on: :collection
  end

  resources :cities do
    post 'set'
    get 'city_capacity', on: :collection
  end

  resources :orders do
    member do
      post 'comment'
    end

    collection do
      get 'new_car_select'
      get 'new_service_select'
      get 'new_info_submit'

      get 'select_car'
      get 'select_item'
      get 'success'
      get 'order_status'

      get 'select_car_by_initial'
      get 'select_car_item'
      get 'auto_brands'
      get 'auto_series'
      get 'auto_model_numbers'
      get 'place_order_page'

      post 'refresh_price'
      post 'place_order'
      post 'submit'
      post 'validate_preferential_code'
      post 'no_preferential'
      get  'no_car_type'
      post 'submit_no_car_order'
      get  'pay_show'
      post 'pay'
      get 'notify'
    end
  end

  resources :users do
    collection do
      get 'orders'
      get 'orders_detail'
      get 'discounts'
      get 'maintain_histories_list'
      get 'maintain_history'
      get 'cars'
      get 'balance'
      get 'settings'
      get 'get_user_info'
    end
  end

  resources :service_addresses do
    post 'set_default'
  end

  resources :autos

  root to: 'home#new_index'

  resources :sessions do
    get 'callback',  on: :collection
    get 'notify', on: :collection
    delete 'destroy', on: :collection
  end

  namespace :admin do
    root to: 'main#index'
    resources :main
    resources :activities
    resources :channels
    resources :users
    resources :posts
    resources :cities
    resources :products
    resources :public_accounts do
      collection do
        get 'apply_menu' => 'public_accounts#apply_menu'
        get 'diy_menu' => 'public_accounts#diy_menu'
        get 'edit_menu' => 'public_accounts#edit_menu'
        post ':id/update_menu' => 'public_accounts#update_menu', as: 'update_menu'
      end
    end
    resources :qrcodes
    resources :weixin
    resources :reply_messages do
      resources :reply_articles
    end
  end

  namespace :activity do
    resources :main do
      collection do
        get 'select_city'
      end
    end
  end

  resources :phones do
    post :send_verification_code, on: :collection
  end

  get 'activities/:name' => 'activity/main#show', as: 'activity'
end

app/controllers/activity/home_controller.rb
class Activity::HomeController < ActionController::Base
  layout "activity"
  impressionist

  before_action :find_activity

  def show
    impressionist(@activity, params[:from])

    if @activity && Time.now < @activity.end_date && Time.now > @activity.start_date
      render "#{@activity.name}"
    else
      render text: "no such activity"
    end
  end

  private

  def find_activity
    @activity = Activity.find_by name: params[:name]
    return render text: "no such activity" unless @activity
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ActionController::Base
  layout "admin"
  http_basic_authenticate_with name: 'admin', password: 'KaLaDing'

  def index
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    unless browser.mobile?
      return redirect_to '/'
    end
  end

  def new_index
    if browser.mobile?
      if session[:from_path]
        return redirect_to action: :index, login: 1
      else
        return redirect_to action: :index
      end
    end
    render layout: "new"
  end
end

app/helpers/activity/home_helper.rb
module Activity::HomeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html+phone.erb
<% cache ["home-phone", current_city_name] do %>
  <div class="home-phone phone-page">

    <div class="home-header">
      <div class="section">
        <div class="cell clearfix">
          <div class="brand pull-left">
            <%= link_to '/' do %>
              <%= image_tag 'logo-mobile.png' %>
            <% end %>
          </div>

          <div class="pull-right curr-city">
            <a href="#" id="current_city">
              <span class="location">
                <%= image_tag "location-pin.png" %>
              </span>

              <span class="city-name">
                <%= current_city_name %>
              </span>
            </a>
          </div>
        </div>
      </div>
    </div>


    <div class="carousel slide flexslider">
      <ul class="slides">
        <li>
          <%= link_to select_car_item_orders_path(type: 'pm25') do %>
            <%= image_tag("phone-home/banner/banner-1.jpg")%>
          <% end %>
        </li>
        <li>
          <%= link_to select_car_item_orders_path(type: 'pm25') do %>
            <%= image_tag("phone-home/banner/banner-2.jpg")%>
          <% end %>
        </li>
      </ul>
    </div>

    <div class="items clearfix">
      <div class="left">
        <div class="pm25 item" data-type="pm25">
          <%= link_to select_car_item_orders_path(type: 'pm25') do %>
            <%= image_tag("phone-home/pm25.png") %>
            <p class="tit">车内防霾滤芯</p>
            <p class="con">告别重度雾霾</p>
          <% end %>
        </div>

        <div class="bty item" data-type="bty">
          <%= link_to select_car_item_orders_path(type: 'bty') do %>
            <%= image_tag("phone-home/bty.png") %>
            <p class="tit">更换电瓶</p>
            <p class="con">搭电救援</p>
          <% end %>
        </div>
      </div>

      <div class="right">
        <div class="smt item" data-type="smt">
          <%= link_to select_car_item_orders_path(type: 'smt') do %>
            <%= image_tag("phone-home/smt.png") %>
            <p class="tit">机油机滤</p>
            <p class="con">更换机油、机滤</p>
          <% end %>
        </div>

        <div class="bmt item" data-type="bmt">
          <%= link_to select_car_item_orders_path(type: 'bmt') do %>
            <%= image_tag("phone-home/bmt.png") %>
            <p class="tit">机油三滤</p>
            <p class="con">机油三滤+32项检测</p>
          <% end %>
        </div>
      </div>


      <div class="left">
        <div class="item tmp" data-type="air-clean">
          <%= link_to no_car_type_orders_path(type: '3') do %>
            <p >空调风道清洗</p>
          <% end %>
        </div>

        <div class="item tmp" data-type="engine-clean">
          <%= link_to no_car_type_orders_path(type: '4') do %>
            <p >发动机舱清洁</p>
          <% end %>
        </div>
      </div>

      <div class="right">
        <div class="item tmp" data-type="tire-mt">
          <%= link_to no_car_type_orders_path(type: '5') do %>
            <p >轮胎养护</p>
          <% end %>
        </div>

        <div class="item tmp" data-type="dtc">
          <%= link_to no_car_type_orders_path(type: '6') do %>
            <p >车辆安全检测</p>
          <% end %>
        </div>
      </div>

    </div>

    <%= render "shared/footer" %>

  </div>
<% end %>

app/views/home/index.html.erb
<% cache ["home", "version1"] do %>
  <%= title "首页" %>
  <%#= link_to "创建订单", select_car_orders_path %>
  <%# if signed_in? %>
    <!-- 你已经使用<%#= current_user.nickname %>的账户登陆 -->
  <%# else %>
    <!-- 没登陆 -->
  <%# end %>
  <div class="home-page index">
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        <li data-target="#carousel-example-generic" data-slide-to="3"></li>
        <li data-target="#carousel-example-generic" data-slide-to="4"></li>
        <!-- <li data&#45;target="#carousel&#45;example&#45;generic" data&#45;slide&#45;to="4"></li> -->
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <%= image_tag("slider4.jpg")%>
        </div>
        <div class="item">
          <%= image_tag("slider1.jpg")%>
        </div>
        <div class="item">
          <%= image_tag("slider2.jpg")%>
        </div>
        <div class="item">
          <%= image_tag("slider3.jpg")%>
        </div>
        <div class="item">
          <%= image_tag("activity/tiantian/pc-banner.jpg")%>
        </div>
      </div>
      <!-- <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a> -->
    </div>
    <div class="select-car">
      <%= render "shared/select_car" %>
      <a id="next_step" class="btn btn-default">立即预约</a>
      <%= link_to "没找到车型？", no_car_type_orders_path %>
    </div>
    <div class="container">
      <div class="product">
        <h3 class="title" title="产品与服务">产品与服务</h3>
        <div class="content maintain-item">
          <dl>
            <dt class="bac-white">
            <%= image_tag("menu1.jpg", :class=> "logo")%>
            </dt>
            <dd class="bac"></dd>
            <dd class="con">
            <h4 class="item-title" title="卡拉丁空调滤清器">卡拉丁空调滤清器</h4>
            <span class="description" title="3分钟告别车内雾霾">3分钟告别车内雾霾</span>
            <a href="/orders/select_car?type=pm25">
              <button class="order-btn" title="立即预定">立即预定</button>
            </a>
            </dd>
          </dl>
          <dl>
            <dt class="bac-white">
            <%= image_tag("menu2.jpg", :class=> "logo")%>
            </dt>
            <dd class="bac"></dd>
            <dd class="con">
            <h4 class="item-title" title="卡拉丁空调滤清器">卡拉丁上门大保养</h4>
            <span class="description" title="3分钟告别车内雾霾"> 省时、省心、省钱 </span>
            <a href="/orders/select_car?type=bmt">
              <button class="order-btn" title="立即预定">立即预定</button>
            </a>
            </dd>
          </dl>
          <dl>
            <dt class="bac-white">
              <%= image_tag("menu3.jpg", :class=> "logo")%>
            </dt>
            <dd class="bac"></dd>
            <dd class="con">
            <h4 class="item-title" title="卡拉丁空调滤清器">卡拉丁上门小保养</h4>
            <span class="description" title="3分钟告别车内雾霾">3分钟告别车内雾霾</span>
            <a href="/orders/select_car?type=smt">
              <button class="order-btn" title="立即预定">立即预定</button>
            </a>
            </dd>
          </dl>
        </div>
      </div>
      <div class="maintain-process">
        <h3 class="title" title="服务流程">服务流程</h3>
        <ul class="content number">
          <li class="shot"><span></span><var></var></li>
          <li><span title="预定服务">1</span><var></var></li>
          <li><span title="订单审核">2</span><var></var></li>
          <li><span title="技师上门">3</span><var></var></li>
          <li><span title="保养检测">4</span><var></var></li>
          <li><span title="订单完成">5</span><var></var></li>
          <li class="last"><span title="检测报告">6</span></li>
          <li class="shot"><var></var><span></span></li>
        </ul>
        <ul class="item">
          <li>
            <h4 title="预定服务">预定服务</h4>
            <span>您可以通过官网、微信服务号、服务热线、预订服务</span>
          </li>
          <li>
            <h4 title="订单审核">订单审核</h4>
            <span>订单预订成功后，客服会通过电话或者短信审核确认</span>
          </li>
          <li>
            <h4 title="技师上门">技师上门</h4>
            <span>我们的小卡技师会提前预约，给您的爱车进行上门服务</span>
          </li>
          <li>
            <h4 title="保养检测">保养检测</h4>
            <span>服务包括保养服务或滤芯服务，并有全车32项安全检查</span>
          </li>
          <li>
            <h4 title="订单完成">订单完成</h4>
            <span>当小卡技师为您服务完毕后，您可以进行现场结账</span>
          </li>
          <li>
            <h4 title="检测报告">检测报告</h4>
            <span>订单完成后，您可以到微信/网站的个人中心，查看车检报告</span>
          </li>
        </ul>
      </div>
      <div class="knowlege">
        <h3 class="title" title="知识普及">知识普及</h3>
        <div class="content">
          <div class="left">
            <div class="des">
              <h4>卡拉丁车用空调滤清器——车内雾霾终极解决方案</h4>
              <p>
                PM2.5指细颗粒物指环境空气中空气动力学当量直径小于等于 2.5 微米的颗粒物。它能较长时间悬浮于空气中，与较粗的大气颗粒物相比，PM2.5粒径小，面积大，活性强，易附带有毒、有害物质（例如，重金属、微生物等），且在大气中的停留时间长、输送距离远，对人体健康和大气环境质量的影响更大。
              </p>
              <p>
                卡拉丁车用空调滤清器PM2.5过滤效果最高可达99%，无论车外空气环境多恶劣，都能让车内PM2.5浓度在50以内，达国家一级优良空气标准...
                <%= link_to "查看更多>>", '#',:class=>'more' %>
              </p>
            </div>
            <%= image_tag("k1.png", :class=> "k1")%>
          </div>
          <div class="right">
            <%= image_tag("k2.png", :class=> "k2")%>
            <div class="des">
              <h4>卡拉汽车上门保养——您的车辆保养专家</h4>
              <p>
                汽车保养是指根据车辆各部位不同材料所需的保养条件，采用不同性质的专用护理材料和产品，对汽车进行全新的保养护理的工艺过程。
              </p>
              <p>
                掌握一定的汽车保养常识是车主用车的基本技能，在日常生活中，通常随着驾龄的延长，大家对汽车保养的了解也随之加深，很多大小问题可以及时发现，以便快速解决。
              </p>
              <p>
                卡拉丁有最专业的技术，给您带去最好的保养服务，点击查看更多学习更多保养知识...
                <%= link_to "查看更多>>", '#',:class=>'more' %>
              </p>
            </div>
          </div>
        </div>
      </div>
      <div class="menu">
        <h3 class="title" title="关于我们">关于我们</h3>
        <div class="content">
          <ul>
            <li class="pm">
              <%= image_tag("about1.png", :class=> "picc")%>
              <%#= link_to "PM2.5滤芯", '', target: "_blank", :title => "PM2.5滤芯" %>
            </li>
            <li class="know">
              <%= image_tag("about2.png", :class=> "picc")%>
              <%#= link_to "用车知识", '', target: "_blank", :title => "用车知识" %>
              <!-- post_page_path(id: 12) -->
            </li>
            <li class="report">
              <%= image_tag("about3.png", :class=> "picc")%>
              <%#= link_to "车检报告", '', target: "_blank", :title => "车检报告" %>
            </li>
          </ul>
          <p>
            卡拉丁，成立于2012年，是一家通过汽车养护技术研发与创新，并与移动互联网技术平台相结合，为广大汽车用户提供便捷养护服务的创新型汽车后市场服务提供商。卡拉丁是我国首家提出并形成规模化的上门汽车保养服务商，是汽车保养O2O理念的践行者。
          </p>
          <p>
            “便捷、专注、可靠”是卡拉丁的服务理念。卡拉丁人以“价值、分享、责任”为创业理念，为用户创造价值，让员工分享成长，力所能及地贡献社会。
          </p>
          <p>
            上门汽车保养、上门汽车安全检测、上门更换车用防霾空调滤清器是卡拉丁现有三大标准化产品。卡拉丁自主研发的防霾空调滤芯，安装后防霾效果达95%+，让车内空气质量可达到国家一级标准。
            <%= link_to "查看更多>>", '#', :class=>'more'  %>
          </p>
        </div>
      </div>
      <div class="award">
        <h3 class="title" title="获奖展示">获奖展示</h3>
        <div class="content">
          <dl>
            <dt></dt>
            <dd>
              <p>
              获得创业家评选的最值得投资的服务业O2O公司TOP10之一，
              我们给用户节约的去4S店保养的时间，更重要的是我们保养报价要比4S店低30%-50%...
                <%= link_to "查看更多>>", slug_posts_path(15, 'news'), :class=>'more'  %>
              </p>
              <span class="num">No.1</span>
            </dd>
          </dl>
          <dl>
            <dt></dt>
            <dd>
              <p>
              卡拉丁是国内最先提出汽车上门保养的概念并付诸实现的公司，
              自主研发的活性炭空调滤清器PM2.5过滤效果达95%，达到国家一级优良空气标注...
                <%= link_to "查看更多>>", slug_posts_path(15, 'news'), :class=>'more'  %>
              </p>
              <span class="num">No.2</span>
            </dd>
          </dl>
          <dl>
            <dt></dt>
            <dd>
              <p>
              在“2014年度风云榜”中，卡拉丁获得”最佳创业公司”称号，卡拉丁也是国内最早进入上门保养行业的服务商...
                <%= link_to "查看更多>>", slug_posts_path(15, 'news'), :class=>'more'  %>
              </p>
              <span class="num">No.3</span>
            </dd>
          </dl>
          <dl>
            <dt></dt>
            <dd>
              <p>
              在2014年世界O2O博览会上，卡拉丁获得2014年全球最具影响力O2O出行类应用奖...
                <%= link_to "查看更多>>", slug_posts_path(15, 'news'), :class=>'more'  %>
              </p>
              <span class="num">No.4</span>
            </dd>
          </dl>
        </div>
      </div>
      <div class="guest">
        <h3 class="title" title="集团客户">集团客户</h3>
        <ul class="content">
          <li title="">
            <a href="#">
              <%= image_tag("picc.png", :class=> "picc")%>
            </a>
          </li>
          <li title="">
            <a href="#">
              <%= image_tag("d.png", :class=> "d")%>
            </a>
          </li>
          <li title="">
            <a href="#">
              <%= image_tag("m.png", :class=> "m")%>
            </a>
          </li>
          <li title="">
            <a href="#">
              <%= image_tag("axa.png", :class=> "axa")%>
            </a>
          </li>
          <li title="">
            <a href="#">
              <%= image_tag("blue.png", :class=> "blue")%>
            </a>
          </li>
        </ul>
      </div>

      <% cache City.all.map(&:updated_at) do %>
        <div class="area">
          <h3 class="title" title="服务区域">服务区域</h3>
          <div class="content">
            <%= image_tag("map.png")%>
            <ul>
              <% City.all.each do |city| %>
                <li>
                  <a class="tit" href="#"><%= city.name %></a>
                  <span><%= city.district_desc %></span>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>
    </div>
  </div>

<% end %>

app/views/home/new_index.html.erb
<% cache "new_home_index" do %>
  <div class="new-index">
    <%#= image_tag("new-index/wrench.png",:class => 'wrench translate-wrench')%>
    <%#= image_tag("new-index/erwei.jpg",:class => 'erwei')%>
    <div class="con">
      <div class="product">
        <h4 class="tit"><span>产品服务</span>
          <!--
            <p class="rank">
              <span>第</span>
              <span class="num">232323</span>
              <span>位 感谢您的信赖</span>
            </p>
            -->
        </h4>
        <ul class="main clearfix">
          <li>
            <a href="/orders/new_car_select?type=bmt">
              <p class="key hide">机油三滤</p>
              <%= image_tag("new-index/bmt1.png",:class => 'pic1')%>
              <%= image_tag("new-index/bmt2.png",:class => 'pic2 hide')%>
            </a>
          </li>
          <li>
            <a href="/orders/new_car_select?type=smt">
              <p class="key hide">机油机滤</p>
              <%= image_tag("new-index/smt1.png",:class => 'pic1')%>
              <%= image_tag("new-index/smt2.png",:class => 'pic2 hide')%>
            </a>
          </li>
          <li>
            <a href="/orders/new_car_select?type=pm25">
              <p class="key hide">空调滤清器</p>
              <%= image_tag("new-index/pm25.png",:class => 'pic1')%>
              <%= image_tag("new-index/pm252.png",:class => 'pic2 hide')%>
            </a>
          </li>
          <li>
            <a href="/orders/new_car_select?type=bty">
              <p class="key hide">更换电瓶</p>
              <%= image_tag("new-index/battery1.png",:class => 'pic1')%>
              <%= image_tag("new-index/battery2.png",:class => 'pic2 hide')%>
            </a>
          </li>

          <!--
          <li class="spe">
            <%#= image_tag("new-index/customer-num.png",:class => 'customer-num')%>
            <p class="rank"><span>第</span><span class="num">232323</span><span>位</span></p>
            <p>感谢您的信赖</p>
          </li>
          -->
        </ul>
      </div>
      <!-- <div class="activity">
        <h4 class="tit">活动专区</h4>
        <ul class="main clearfix">
          <li>
            <%= image_tag("new-index/")%>
            <p>天天用车活动</p>
          </li>
          <li>
            <%= image_tag("new-index/")%>
            <p>天天用车活动</p>
          </li>
          <li>
            <%= image_tag("new-index/")%>
            <p>天天用车活动</p>
          </li>
          <li>
            <%= image_tag("new-index/")%>
            <p>天天用车服务</p>
          </li>
        </ul>
      </div> -->
      <div class="service clearfix">
        <ul>
          <li class="tit">服务支持</li>
          <li>
            <%= link_to "售后政策", slug_posts_path(6, 'terms') %>
          </li>
          <li>
            <%= link_to "产品保障", slug_posts_path(16, 'guarantee') %>
          </li>
          <li>
            <%= link_to "服务说明", slug_posts_path(7, 'services') %>
          </li>
          <li>
            <a href="/static_pages/lian-xi-wo-men">联系我们</a>
          </li>
        </ul>
        <ul>
          <li class="tit">关于我们</li>
          <li>
            <a href="/static_pages/qi-ye-jie-shao">企业介绍</a>
          </li>
          <li>
            <a href="/static_pages/qi-ye-rong-yu">企业荣誉</a>
          </li>
          <li>
            <%= link_to "新闻动态", list_posts_path(tag_id: 15) %>
          </li>
          <li>
            <a href="/static_pages/fu-wu-ke-hu">服务客户</a>
          </li>
        </ul>
        <ul>
          <li class="tit">
            <a href="/static_pages/qi-ye-jie-shao">关于我们</a>
          </li>
          <li>
            <a href="http://weibo.com/u/2394482722" target="_blank">新浪微博</a>
          </li>
          <li id='wechat_qrcode'>官方微信</li>
        </ul>
        <ul>
          <li class="tit">客服热线</li>
          <li>400-006-8181</li>
          <li>周一至周日8:00-18:00</li>
        </ul>
      </div>
    </div>
  </div>

  <div class="modal fade" id="wechat_modal">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <div class="modal-body">
          <%= image_tag "new-index/erwei.jpg" %>
        </div>
      </div>
    </div>
  </div>
<% end %>