config/routes.rb
Rails.application.routes.draw do

  get 'doc/v2'

  mount WeixinRailsMiddleware::Engine, at: "/"
  mount Ckeditor::Engine => '/ckeditor'

  resources :static_pages

  resources :home do
    get 'new_index', on: :collection
  end

  resources :posts do
    collection do
      get 'about_us'
      get 'knowledge'
      get '/:tag_id/:slug', action: 'show', as: 'slug'
      get '/:tag_id', action: 'posts_list', as: 'list'
    end
  end

  resources :wx, controller: :weixin  do
    get 'transform', on: :collection
  end

  resources :cities do
    post 'set'
    get 'city_capacity', on: :collection
  end

  resources :orders do
    member do
      post 'comment'
    end

    collection do
      get 'new_car_select'
      get 'new_service_select'
      get 'new_info_submit'

      get 'select_car'
      get 'select_item'
      get 'success'
      get 'order_status'

      get 'select_car_by_initial'
      get 'select_car_item'
      get 'auto_brands'
      get 'auto_series'
      get 'auto_model_numbers'
      get 'place_order_page'

      post 'refresh_price'
      post 'place_order'
      post 'submit'
      post 'validate_preferential_code'
      post 'no_preferential'
      get  'no_car_type'
      post 'submit_no_car_order'
      get  'pay_show'
      post 'pay'
      get 'notify'
    end
  end

  resources :users do
    collection do
      get 'orders'
      get 'orders_detail'
      get 'discounts'
      get 'maintain_histories_list'
      get 'maintain_history'
      get 'cars'
      get 'balance'
      get 'settings'
      get 'get_user_info'
    end
  end

  resources :service_addresses do
    post 'set_default'
  end

  resources :autos

  root to: 'home#new_index'

  resources :sessions do
    get 'callback',  on: :collection
    get 'notify', on: :collection
    delete 'destroy', on: :collection
  end

  namespace :admin do
    root to: 'main#index'
    resources :main
    resources :activities
    resources :channels
    resources :users
    resources :posts
    resources :cities
    resources :products
    resources :public_accounts do
      collection do
        get 'apply_menu' => 'public_accounts#apply_menu'
        get 'diy_menu' => 'public_accounts#diy_menu'
        get 'edit_menu' => 'public_accounts#edit_menu'
        post ':id/update_menu' => 'public_accounts#update_menu', as: 'update_menu'
      end
    end
    resources :qrcodes
    resources :weixin
    resources :reply_messages do
      resources :reply_articles
    end
  end

  namespace :activity do
    resources :main do
      collection do
        get 'select_city'
      end
    end
  end

  resources :phones do
    post :send_verification_code, on: :collection
  end

  get 'activities/:name' => 'activity/main#show', as: 'activity'
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :city_products
  has_many :cities, through: :city_products

  has_many :activity_products
  has_many :activities, through: :activity_products

  validates :slug, uniqueness: true, presence: true
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::MainController
  inherit_resources

  defaults :resource_class => Product, :route_prefix => 'admin'

  def permitted_params
    {product: params.fetch(:product, {}).permit(:title, :description, :slug, city_ids: [])}
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/admin/products/_form.html.erb
<div class="container">
  <%= form_for [:admin, resource] do |f| %>
    <% if resource.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(resource.errors.count, "error") %> prohibited this admin_channel from being saved:</h2>

        <ul>
        <% resource.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="actions">

      <table class="table">
        <tr>
          <td>标题</td>
          <td><%= f.text_field :title %></td>
        </tr>

        <tr>
          <td>简介</td>
          <td><%= f.text_field :description %></td>
        </tr>

        <tr>
          <td>slug</td>
          <td><%= f.text_field :slug %></td>
        </tr>

        <tr>
          <td>适用城市</td>
          <td>

            <% City.all.each do |city| %>
              <%= city.name %>
              <%= check_box_tag "product[city_ids][]", city.id, resource.cities.include?(city) %>
            <% end %>

          </td>
        </tr>

        <tr>
          <td colspan=2><%= f.submit %></td>
        </tr>

      </table>

    </div>
  <% end %>
</div>

app/views/admin/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_product_path(resource) %> |
<%= link_to 'Back', admin_products_path %>

app/views/admin/products/index.html.erb
<div class="container">
  <table class='table'>
    <thead>
      <tr>
        <th>名称</th>
        <th>简介</th>
        <th>Slug</th>

        <th>展示</th>
        <th>编辑</th>
        <th>删除</th>
      </tr>
    </thead>

    <tbody>
      <% collection.each do |product| %>
        <tr>

          <td><%= product.title %></td>
          <td><%= product.description %></td>
          <td><%= product.slug %></td>

          <td><%= link_to 'Show', admin_product_path(product) %></td>
          <td><%= link_to 'Edit', edit_admin_product_path(product) %></td>
          <td><%= link_to 'Destroy', admin_product_path(product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to '创建', new_admin_product_path %>
</div>

app/views/admin/products/new.html.erb
<h1>new Product</h1>
<%= render 'form' %>

<%= link_to 'Back', admin_products_path %>

app/views/admin/products/show.html.erb
<div class="container">

  <p id="notice"><%= notice %></p>

  <table class='table'>
    <tr>
      <td>名称</td>
      <td><%= resource.title %></td>
    </tr>
    <tr>
      <td>短简介(在首页展示)</td>
      <td><%= resource.description %></td>
    </tr>
    <tr>
      <td>slug(用于url中的type=pm25)</td>
      <td><%= resource.slug %></td>
    </tr>
    <tr>
      <td>适用城市</td>
      <td><%= resource.cities.map(&:name).join(' | ')%></td>
    </tr>
  </table>

  <%= link_to 'Edit', edit_admin_product_path(resource) %> |
  <%= link_to 'Back', admin_products_path %>

</div>