config/routes.rb
Rails.application.routes.draw do

  get 'doc/v2'

  mount WeixinRailsMiddleware::Engine, at: "/"
  mount Ckeditor::Engine => '/ckeditor'

  resources :static_pages

  resources :home do
    get 'new_index', on: :collection
  end

  resources :posts do
    collection do
      get 'about_us'
      get 'knowledge'
      get '/:tag_id/:slug', action: 'show', as: 'slug'
      get '/:tag_id', action: 'posts_list', as: 'list'
    end
  end

  resources :wx, controller: :weixin  do
    get 'transform', on: :collection
  end

  resources :cities do
    post 'set'
    get 'city_capacity', on: :collection
  end

  resources :orders do
    member do
      post 'comment'
    end

    collection do
      get 'new_car_select'
      get 'new_service_select'
      get 'new_info_submit'

      get 'select_car'
      get 'select_item'
      get 'success'
      get 'order_status'

      get 'select_car_by_initial'
      get 'select_car_item'
      get 'auto_brands'
      get 'auto_series'
      get 'auto_model_numbers'
      get 'place_order_page'

      post 'refresh_price'
      post 'place_order'
      post 'submit'
      post 'validate_preferential_code'
      post 'no_preferential'
      get  'no_car_type'
      post 'submit_no_car_order'
      get  'pay_show'
      post 'pay'
      get 'notify'
    end
  end

  resources :users do
    collection do
      get 'orders'
      get 'orders_detail'
      get 'discounts'
      get 'maintain_histories_list'
      get 'maintain_history'
      get 'cars'
      get 'balance'
      get 'settings'
      get 'get_user_info'
    end
  end

  resources :service_addresses do
    post 'set_default'
  end

  resources :autos

  root to: 'home#new_index'

  resources :sessions do
    get 'callback',  on: :collection
    get 'notify', on: :collection
    delete 'destroy', on: :collection
  end

  namespace :admin do
    root to: 'main#index'
    resources :main
    resources :activities
    resources :channels
    resources :users
    resources :posts
    resources :cities
    resources :products
    resources :public_accounts do
      collection do
        get 'apply_menu' => 'public_accounts#apply_menu'
        get 'diy_menu' => 'public_accounts#diy_menu'
        get 'edit_menu' => 'public_accounts#edit_menu'
        post ':id/update_menu' => 'public_accounts#update_menu', as: 'update_menu'
      end
    end
    resources :qrcodes
    resources :weixin
    resources :reply_messages do
      resources :reply_articles
    end
  end

  namespace :activity do
    resources :main do
      collection do
        get 'select_city'
      end
    end
  end

  resources :phones do
    post :send_verification_code, on: :collection
  end

  get 'activities/:name' => 'activity/main#show', as: 'activity'
end

app/models/reply_message.rb
class ReplyMessage < ActiveRecord::Base
  belongs_to :public_account
  has_many :reply_articles, dependent: :destroy

  validates_uniqueness_of :keyword
  validates :keyword, :msg_type,  presence:true

  def reply_message
    self.send("reply_#{msg_type}_message")
  end

  private
  def reply_text_message
    content
  end

  def reply_news_message
    reply_articles.all
  end

end

app/controllers/admin/reply_messages_controller.rb
class Admin::ReplyMessagesController < Admin::MainController

  def index
    @reply_messages = ReplyMessage.all
  end

  def new
    @reply_message = ReplyMessage.new
  end

  def show
    @reply_message = ReplyMessage.find params[:id]
  end

  def edit
    @reply_message = ReplyMessage.find params[:id]
  end

  def create
    account = PublicAccount.find_by(name:"kaladingcom")
    @reply_message = account.reply_messages.new message_params
    if @reply_message.save
      redirect_to admin_reply_message_path(@reply_message.id)
    else
      render 'new'
    end
  end

  def update
    @reply_message = ReplyMessage.find params[:id]
    @reply_message.update message_params

    if @reply_message.save
      redirect_to admin_reply_messages_path
    else
      render 'edit'
    end
  end

  def destroy
    @reply_message = ReplyMessage.find params[:id]
    if @reply_message.destroy
      redirect_to admin_reply_messages_path
    end
  end

  private
  def message_params
    params.require(:reply_message).permit(:content, :keyword, :msg_type)
  end
end

app/views/admin/reply_messages/_form.html.erb
<div class="form-group">
  <%= render 'text_form' %>
</div>

app/views/admin/reply_messages/_show_news.html.erb
<table class="table">
  <thead>
    <tr>
      <th>消息标题</th>
      <th>图片链接</th>
      <th>跳转链接</th>
      <th>消息描述</th>
      <th>编辑</th>
      <th>删除</th>
    </tr>
  </thead>

  <tbody>
    <% @reply_message.reply_articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.pic.url %></td>
        <td><%= article.url %></td>
        <td><%= article.description %></td>
        <td><%= link_to "修改", edit_admin_reply_message_reply_article_path(@reply_message.id, article.id) %></td>
        <td><%= link_to "删除", admin_reply_message_reply_article_path(@reply_message, article.id), method: :delete, data:{ confirm: '你特么确定要删除我吗?'} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/reply_messages/_text_form.html.erb
<%= form_for [:admin, @reply_message] do |f| %>

  <div class="form-group">
    <label>内容：</label>
    <%= f.text_area :content, rows:10, class: 'form-control' %>
  </div>

  <div class="submit-btn">
      <%= f.submit '保存' , class: 'btn btn-default' %>
  </div>

<% end %>

app/views/admin/reply_messages/edit.html.erb
<div class="container">
<%= form_for [:admin, @reply_message] do |f| %>
  <% if @reply_message.errors.any? %>
    <div id="error_explanation" class="for-group has-error">
      <h2><%= pluralize(@reply_message.errors.count, "error") %> prohibited this reply_message from being saved:</h2>
      <ul>
        <% @reply_message.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label>关键字</label>
    <%= f.text_field :keyword, class: 'form-control' %>
  </div>

  <div class="form-group">
    <label>类型</label>
    <%= f.text_field :msg_type, readonly: true,class: 'form-control' %>
  </div>

  <div class="submit-btn">
      <%= f.submit '保存' , class: 'btn btn-default' %>
  </div>

<% end %>

  <%= link_to "返回", admin_reply_messages_path %>
</div>

app/views/admin/reply_messages/index.html.erb
<div class="container">
  <ul>
    注意事项：
    <li>
      auto_reply_msg关键字为早八点至晚二十点以后消息自动回复关键字，类型固定为text。除内容可编辑以外，其他不可更改，更不可删除！
    </li>
    <li>
      follow_reply_msg关键字为用户第一次关注时消息回复关键字，类型固定为text。除内容可编辑以外，其他不可更改，更不可删除！
    </li>
  </ul>
  <table class="table">
    <thead>
      <tr>
        <th>关键字</th>
        <th>类型</th>
        <th>修改关键字</th>
        <th>回复消息</th>
        <th>删除</th>
      </tr>
    </thead>

    <tbody>
      <% @reply_messages.each do |msg| %>
        <tr>
          <td><%= msg.keyword %></td>
          <td><%= msg.msg_type %></td>
          <td><%= link_to "修改", edit_admin_reply_message_path(msg.id) %></td>
          <td><%= link_to "编辑", admin_reply_message_path(msg.id) %></td>
          <td><%= link_to "删除", admin_reply_message_path(msg.id), method: :delete, data:{ confirm: '你特么确定要删除我吗?'} %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to "添加", new_admin_reply_message_path %> |
  <%= link_to "返回", admin_weixin_index_path %>
</div>

app/views/admin/reply_messages/new.html.erb
<div class="container">
  <%= form_for [:admin, @reply_message] do |f| %>
  <% if @reply_message.errors.any? %>
    <div id="error_explanation" class="for-group has-error">
      <h2><%= pluralize(@reply_message.errors.count, "error") %> prohibited this reply_message from being saved:</h2>
      <ul>
        <% @reply_message.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label>关键字</label>
    <%= f.text_field :keyword, class: 'form-control' %>
  </div>

  <div class="form-group">
    <label>类型(注意:此项创建完成后不可更改)</label>
    <%= f.select :msg_type, options_for_select([['text', 'text'], ['news', 'news']]),{}, {class: 'form-control'} %>
  </div>

  <div class="submit-btn">
      <%= f.submit '保存' , class: 'btn btn-default' %>
  </div>
  <% end %>
  <%= link_to "返回", admin_reply_messages_path %>
</div>

app/views/admin/reply_messages/show.html.erb
<div class="container">
  <div class="form-group">
    <label>关键字：</label>
    <%= @reply_message.keyword %>
  </div>

  <div class="form-group">
    <label>类型：</label>
    <%= @reply_message.msg_type %>
  </div>

  <% if @reply_message.msg_type == 'text' %>
    <%= render 'text_form' %>
  <% elsif @reply_message.msg_type == 'news' %>
    <%= render 'show_news' %>
    <%= link_to "添加", new_admin_reply_message_reply_article_path(@reply_message.id) %> |
  <% end %>

  <%= link_to "返回", admin_reply_messages_path %>
</div>